#### Import Libraries

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

#### Import Dataset

In [2]:
df = pd.read_csv('cleaned_data.csv')

#### Divide into X and Y

In [3]:
X = df.drop(columns = ['Outcome'])
y = df[['Outcome']]

#### feature Scaling

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = pd.DataFrame(data = sc.fit_transform(X), columns = X.columns)

#### Divide into train and test

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [6]:
print(y_train['Outcome'].value_counts())
print(y_test['Outcome'].value_counts())

Outcome
0    449
1    242
Name: count, dtype: int64
Outcome
0    51
1    26
Name: count, dtype: int64


#### library to install for SMOTE
#### pip install imblearn

#### Lets Create balanced data in training using SMOTE

In [7]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state = 42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

In [8]:
y_resampled['Outcome'].value_counts()

Outcome
0    449
1    449
Name: count, dtype: int64

In [9]:
# Build model and train - LogisticRegression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_resampled, y_resampled)

# Evaluate Model
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = model.predict(X_test)
y_pred = pd.DataFrame(data = y_pred, columns = ['Prediction'])
result = pd.concat([y_test.reset_index(drop = True), y_pred],axis = 1)
cm = confusion_matrix(result['Outcome'], result['Prediction'])
score = accuracy_score(result['Outcome'], result['Prediction'])
print(cm)
print(score)

[[39 12]
 [ 3 23]]
0.8051948051948052


In [10]:
# Build and train model - DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier
model_dt = DecisionTreeClassifier(criterion = 'gini')
model_dt.fit(X_resampled, y_resampled)

# Evaluate Model
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = model.predict(X_test)
y_pred = pd.DataFrame(data = y_pred, columns = ['Prediction'])
result = pd.concat([y_test.reset_index(drop = True), y_pred],axis = 1)
cm = confusion_matrix(result['Outcome'], result['Prediction'])
score = accuracy_score(result['Outcome'], result['Prediction'])
print(cm)
print(score)

[[39 12]
 [ 3 23]]
0.8051948051948052


In [11]:
# Build and train model - RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(n_estimators = 101)
model_rf.fit(X_resampled, y_resampled)

# Evaluate Model
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = model_rf.predict(X_test)
y_pred = pd.DataFrame(data = y_pred, columns = ['Prediction'])
result = pd.concat([y_test.reset_index(drop = True), y_pred],axis = 1)
cm = confusion_matrix(result['Outcome'], result['Prediction'])
score = accuracy_score(result['Outcome'], result['Prediction'])
print(cm)
print(score)

[[40 11]
 [ 6 20]]
0.7792207792207793


In [12]:
# Build and train model - KNN
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
model_knn.fit(X_resampled, y_resampled)

# Evaluate Model
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = model_rf.predict(X_test)
y_pred = pd.DataFrame(data = y_pred, columns = ['Prediction'])
result = pd.concat([y_test.reset_index(drop = True), y_pred],axis = 1)
cm = confusion_matrix(result['Outcome'], result['Prediction'])
score = accuracy_score(result['Outcome'], result['Prediction'])
print(cm)
print(score)

[[40 11]
 [ 6 20]]
0.7792207792207793


In [13]:
# Build and train model - GaussianNB
from sklearn.naive_bayes import GaussianNB
model_nb = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
model_nb.fit(X_resampled, y_resampled)

# Evaluate Model
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = model_nb.predict(X_test)
y_pred = pd.DataFrame(data = y_pred, columns = ['Prediction'])
result = pd.concat([y_test.reset_index(drop = True), y_pred],axis = 1)
cm = confusion_matrix(result['Outcome'], result['Prediction'])
score = accuracy_score(result['Outcome'], result['Prediction'])
print(cm)
print(score)

[[38 13]
 [ 3 23]]
0.7922077922077922


In [14]:
# Build and train model - SVC
from sklearn.svm import SVC
model_svc = SVC(kernel = 'rbf')
model_svc.fit(X_resampled, y_resampled)

# Evaluate Model
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = model_svc.predict(X_test)
y_pred = pd.DataFrame(data = y_pred, columns = ['Prediction'])
result = pd.concat([y_test.reset_index(drop = True), y_pred],axis = 1)
cm = confusion_matrix(result['Outcome'], result['Prediction'])
score = accuracy_score(result['Outcome'], result['Prediction'])
print(cm)
print(score)

[[38 13]
 [ 5 21]]
0.7662337662337663


#### Accuracy Score of Random Forest Algo is Large so Choose to Export this Model

In [15]:
import pickle
pickle.dump(model_rf, open('model.pkl', 'wb'))
pickle.dump(sc, open('sc.pkl', 'wb'))

In [16]:
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age'] 
myinput = [[10, 150, 80, 35, 130, 30, 0.65, 55]]
myinput = pd.DataFrame(data = myinput, columns = columns)
myinput = pd. DataFrame (data = sc.transform(myinput), columns = columns)
result = model_rf.predict(myinput) 
if result[0] == 0:
   print("No, patient is not diabetic")
else:
   print("Yes, patient is diabetic")

Yes, patient is diabetic
